insert into projekt.bolidy(Numer_startowy, TEAM_ID, typ, nazwa, wynik_overal) values
            (43, 1, 'EV', 'LEM',1),
            (23, 3, 'EV', 'ELECTRIC_RUN',4),
            (8, 2, 'EV', 'ELE2.0',2),
            (4, 4, 'EV', 'RTE2.0',3),
            (128, 11, 'EV', 'Velocity Vortex', 5),
            (132, 50, 'CV', 'Quantum Racer', 6),
            (95, 8, 'EV', 'Turbo Titan', 7),
            (80, 2, 'EV', 'Electra Blitz', 8),
            (12, 38, 'CV', 'Fusion Flash', 9),
            (140, 40, 'EV', 'Sonic Surge', 10),
            (199, 41, 'EV', 'Cyclone Charger', 11);

insert into projekt.zespoly
        values (1, 'AGH Racing', 'AGH Cracow', 'PL', 1),
        (2, 'TUfast Racing Team e-Technology', 'München TU', 'DE', 7),
        (3, 'Ecurie Aix Formula Student Team RWTH Aachen e.V.', 'Aachen RWTH', 'DE', 9),
        (4, 'NTHU Racing', 'Hsinchu NTHU', 'TW', 11),
        (5, 'TU Darmstadt Racing Team e.V.', 'Darmstadt TU', 'DE', 26),
        (6, 'StarkStrom Augsburg', 'Augsburg UAS', 'DE', 36),
        (7, 'Mainfranken Racing', 'Schweinfurt UAS', 'DE', 42),
        (8, 'GreenTeam Uni Stuttgart', 'Stuttgart U', 'DE', 30),
        (9, 'Fast Forest', 'Deggendorf IT', 'DE', 27),
        (10, 'Revolve NTNU', 'Trondheim NTNU', 'NO', 17),
        (11, 'Dynamis PRC', 'Milano PT', 'IT', 19);

insert into projekt.czlonkowie
        values  (1, 'Jan', 'Kowalski', 'CEO', 1),
                (2, 'Adam', 'Nowak', 'CTO EV', 1),
                (3, 'Jan', 'Huniek', 'CTO CV', 1),
                (4, 'Krzysztof', 'Ramaniak', 'PM SUSPENSION', 1),
                (5, 'Cristian', 'Hund', 'CTO CV', 2),
                (6, 'Mathias', 'Raus',NULL,2),
                (7, 'Franz', 'Schulz', 'CEO', 2),
                (8, 'Andreas', 'Müller', 'PM Chasis', 2),
                (9, 'Eva', 'Huniek', 'DPM Aerodynamics', 3),
                (10, 'Julian', 'Mark', 'Electrincis Member', 3),
                (11, 'Heinz', 'Fischer', 'Embedded Developer', 4),
                (12, 'Monika', 'Wagner', 'Marketing Member', 4),
                (13, 'Lorie', 'Marivic', 'DPM Chasis', 7),
                (14, 'Nelina', 'Chae', 'PM Steering', 6),
                (15, 'Elbio', 'Zurabi', 'Member Buisness', 8),
                (16, 'Nivaldo', 'Herb', 'Chasis Member', 11),
                (17, 'Jianyan', 'Ehtisham', 'DPM Aerodynamics', 10),
                (18, 'Bulah', 'Gaofeng', 'PM Accumulator', 8),
                (19, 'Weronika', 'Nuti', 'PM Suspension', 11),
                (20, 'Lan', 'Livius', 'Member Buisness', 6),
                (21, 'Jadilla', 'Nurul', 'DPM Electronics', 8),
                (22, 'Anilda', 'Decorosa', 'Member Suspension', 6),
                (23, 'Antione', 'Boutros', 'Member Electronics', 7),
                (24, 'Yawen', 'Nouredin', 'Member Electronics', 5),
                (25, 'Bobo', 'Floriano', 'PM DV', 8),
                (26, 'Vernon', 'Jessia', 'CTO EV', 5),
                (27, 'Lilioara', 'Bouazza', 'PM Brakes', 9),
                (28, 'Jenni', 'Charki', 'Member ACCU', 10),
                (29, 'Kiryl', 'Eliz', 'DPM Suspension', 9),
                (30, 'Rosalina', 'Mailin', 'PM Powertrain', 8),
                (31, 'Pacifica', 'Moro', 'Marketing Memeber', 10),
                (32, 'Parvoleta', 'Christiana', 'DPM Steering', 10),
                (33, 'Fructuosa', 'Carleen', 'Member EV', 9),
                (34, 'Alethia', 'Insa', 'CTO CV', 10),
                (35, 'Jordon', 'Jiandong', 'Member Powertrain', 8),
                (36, 'Kam', 'Elizebeth', 'DPM DV', 6),
                (37, 'Betsey', 'Karem', 'Member Chasis', 11),
                (38, 'Iveth', 'Vesta', 'Member Powertrain', 7),
                (39, 'Blasida', 'Xufen', 'Member Brakes', 10),
                (40, 'Riera', 'Caroll', 'Member Steering', 10),
                (41, 'Protasio', 'Dinis', 'DPM Accumulator', 6),
                (42, 'Yasser', 'Rod', 'PM Aerodynamics', 7);

insert into projekt.pola_namiotowe values
                (1,  3),
                (2,  7),
                (3,  2),
                (4,  4),
                (5,  6),
                (6,  1),
                (7,  5),
                (8,  8),
                (9,  2),
                (10,  7),
                (11,  1),
                (12,  6),
                (13,  3),
                (14,  5),
                (15,  8),
                (16,  4),
                (17,  6),
                (18,  3),
                (19,  7),
                (20,  2);

insert into projekt.nocleg values
                (1, 'Elmwood Avenue',  456, 1),
                (2, 'Pine Lane',  789, 2),
                (3, 'Cedar Court',  234, 3),
                (4, 'Birch Street',  567, 4),
                (5, 'Maple Drive',  890, 5),
                (6, 'Oak Avenue',  123, 6),
                (7, 'Spruce Lane',  101, 7),
                (8, 'Redwood Road',  888, 8),
                (9, 'Sycamore Drive',  333, 9),
                (10,'Willow Lane',  222, 10),
                (11,'Aspen Avenue',  444, 11),
                (12,'Chestnut Road',  555, 12),
                (13,'Sequoia Lane',  666, 13),
                (14,'Poplar Street',  777, 14),
                (15,'Fir Drive',  676, 15),
                (16,'Pinecone Lane',  999, 16),
                (17,'Oakwood Avenue',  121, 17),
                (18,'Cedar Street',  343, 18),
                (19,'Spruce Lane',  565, 19),
                (20,'Maple Road',  787, 20);