insert into projekt.bolidy(Numer_startowy, TEAM_ID, typ, nazwa, wynik_overal) values
            (43, 1, 'EV', 'LEM',1),
            (23, 3, 'EV', 'ELECTRIC_RUN',4),
            (8, 2, 'EV', 'ELE2.0',2),
            (4, 4, 'EV', 'RTE2.0',3);

insert into projekt.zespoly
        values (1, 'AGH Racing', 'AGH Cracow', 'PL', 1);

insert into projekt.czlonkowie
        values  (1, 'Jan', 'Kowalski', 'CEO', 1),
                (2, 'Adam', 'Nowak', 'CTO EV', 1),
                (3, 'Jan', 'Huniek', 'CTO CV', 1),
                (4, 'Krzysztof', 'Ramaniak', 'PM SUSPENSION', 1),
                (5, 'Cristian', 'Hund', 'CTO CV', 2),
                (6, 'Mathias', 'Raus',NULL,2),
                (7, 'Franz', 'Schulz', 'CEO', 2),
                (8, 'Andreas', 'Müller', 'PM Chasis', 2),
                (9, 'Eva', 'Huniek', 'DPM Aerodynamics', 3),
                (10, 'Julian', 'Mark', 'Electrincis Member', 3),
                (11, 'Heinz', 'Fischer', 'Embedded Developer', 4),
                (12, 'Monika', 'Wagner', 'Marketing Member', 4),
                (13, 'Lorie', 'Marivic', 'DPM Chasis', 7),
                (14, 'Nelina', 'Chae', 'PM Steering', 6),
                (15, 'Elbio', 'Zurabi', 'Member Buisness', 8),
                (16, 'Nivaldo', 'Herb', 'Chasis Member', 11),
                (17, 'Jianyan', 'Ehtisham', 'DPM Aerodynamics', 10),
                (18, 'Bulah', 'Gaofeng', 'PM Accumulator', 8),
                (19, 'Weronika', 'Nuti', 'PM Suspension', 11),
                (20, 'Lan', 'Livius', 'Member Buisness', 6),
                (21, 'Jadilla', 'Nurul', 'DPM Electronics', 8),
                (22, 'Anilda', 'Decorosa', 'Member Suspension', 6),
                (23, 'Antione', 'Boutros', 'Member Electronics', 7),
                (24, 'Yawen', 'Nouredin', 'Member Electronics', 5),
                (25, 'Bobo', 'Floriano', 'PM DV', 8),
                (26, 'Vernon', 'Jessia', 'CTO EV', 5),
                (27, 'Lilioara', 'Bouazza', 'PM Brakes', 9),
                (28, 'Jenni', 'Charki', 'Member ACCU', 10),
                (29, 'Kiryl', 'Eliz', 'DPM Suspension', 9),
                (30, 'Rosalina', 'Mailin', 'PM Powertrain', 8),
                (31, 'Pacifica', 'Moro', 'Marketing Memeber', 10),
                (32, 'Parvoleta', 'Christiana', 'DPM Steering', 10),
                (33, 'Fructuosa', 'Carleen', 'Member EV', 9),
                (34, 'Alethia', 'Insa', 'CTO CV', 10),
                (35, 'Jordon', 'Jiandong', 'Member Powertrain', 8),
                (36, 'Kam', 'Elizebeth', 'DPM DV', 6),
                (37, 'Betsey', 'Karem', 'Member Chasis', 11),
                (38, 'Iveth', 'Vesta', 'Member Powertrain', 7),
                (39, 'Blasida', 'Xufen', 'Member Brakes', 10),
                (40, 'Riera', 'Caroll', 'Member Steering', 10),
                (41, 'Protasio', 'Dinis', 'DPM Accumulator', 6),
                (42, 'Yasser', 'Rod', 'PM Aerodynamics', 7);
